### ISSUE TITLE
Issue Installing Blade

### ISSUE THREAD

**Issue by Analucar** [PLSysSec/blade-benchmarks#1]
Hello!

I am currently working on a project focusing on spectre vulnerabilities, and during my research, I came across this paper discussing the Blade tool. While reading the paper, I was impressed by the insightful study presented and realized the significant value it would bring to my project. Therefore, I decided to install the Blade tool and incorporate it into my work. After following all the steps to install the repository and other required tools, I encountered the issue below when executing the `make build` command for the project.

```
/home/docker/wasi-sdk/wasi-sdk-12.0/bin/clang` -O3 -I/home/docker/hacl-star/dist/kremlin/include -I/home/docker/hacl-star/dist/kremlin/kremlib/dist/minimal c_src/Hacl_Poly1305_32.c -o wasm_src/Hacl_Poly1305_32.wasm.unopt -nostartfiles -Wl,--no-entry -Wl,--export-all
In file included from c_src/Hacl_Poly1305_32.c:25:
In file included from c_src/Hacl_Poly1305_32.h:24:
/home/docker/hacl-star/dist/kremlin/include/kremlin/internal/types.h:8:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
Makefile:25: recipe for target 'wasm_src/Hacl_Poly1305_32.wasm.unopt' failed
make: *** [wasm_src/Hacl_Poly1305_32.wasm.unopt] Error 1
```

I suspected that the issue might be related to compatibility between the repository and the other tools, so I attempted to use different versions of each tool. However, even after trying multiple versions, I encountered the same issue. Here are the versions I compiled and installed for each tool:

- lucet-blade - most recent version
- WASI SDK - 12.0 version
- WABT - 1.0.15 version
- Binaryen - 90 version
- HALC - commit de6a314ab

Do you have any suggestions on how I can resolve this issue? Do you have any insights on what might be causing the problem?

Thank you very much for your assistance!

**Comment by Analucar** [comment]
To install the Blade tool, I have created a Dockerfile (below) that compiles and installs all the required tools for Blade, including lucet-blade, WASI SDK, WABT, Binaryen, and HALC. Once I ran this Dockerfile, I made modifications to the Makefile in this repository to ensure the correct paths for these tools are included. Finally, when I executed the `make build` command to build and install Blade, that's when the error shown above occurred.

```
FROM ubuntu:18.04

RUN apt-get update && \
      apt-get -y install sudo

RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

USER docker
CMD /bin/bash

WORKDIR /home/docker

USER root
RUN apt-get update
RUN apt-get -y install build-essential
RUN apt-get -y install software-properties-common
RUN apt-get -y install zip
RUN apt-get -y install wget
RUN apt-get -y install git
RUN apt-get -y install cmake
RUN apt-get -y install clang
RUN apt-get -y install python
RUN apt-get -y install vim
RUN apt-get -y install cargo
RUN wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
RUN gunzip /usr/local/bin/ninja.gz
RUN chmod a+x /usr/local/bin/ninja

USER docker
RUN git clone https://github.com/PLSysSec/blade.git
RUN git clone https://github.com/PLSysSec/lucet-blade.git -b blade
RUN git clone --recursive https://github.com/WebAssembly/wasi-sdk.git
RUN git clone --recursive https://github.com/WebAssembly/wabt.git -b 1.0.15
RUN git clone https://github.com/WebAssembly/binaryen.git -b version_90
RUN git clone https://github.com/hacl-star/hacl-star.git

WORKDIR /home/docker/lucet-blade
RUN git submodule update --init --recursive

WORKDIR /home/docker/wasi-sdk
RUN wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
RUN tar xvf wasi-sdk-12.0-linux.tar.gz

WORKDIR /home/docker/wabt
RUN git submodule update --init
RUN make

WORKDIR /home/docker/binaryen
RUN git submodule init
RUN git submodule update
RUN cmake . && make

WORKDIR /home/docker/hacl-star
RUN git checkout de6a314ab

WORKDIR /home/docker

```

**Comment by maxgallup** [comment]
Hey @Analucar,
I don't know if this will help, but I was able to get further along in the compilation and the only difference to my setup is that I'm using WASI SDK - version 20.0. Might be worth a try.

**Comment by maxgallup** [comment]
@Analucar After digging around for Issue #2 I ran into the same issue you were having and had to change the following line in blade/Makefile:

```
WASI_CLANG_FLAGS=-O3
```
to

```
WASI_CLANG_FLAGS=-O3 --sysroot=$(WASI_SDK)/share/wasi-sysroot
```

**Comment by Analucar** [comment]
Thank you so much for your help @maxgallup! However, as I tried to compile the tool with `make build` I encountered the issue below. 

```
/home/docker/wasi-sdk/wasi-sdk-12.0/bin/clang -O3 --sysroot=/home/docker/wasi-sdk/share/wasi-sysroot -I/home/docker/hacl-star/dist/kremlin/include -I/home/docker/hacl-star/dist/kremlin/kremlib/dist/minimal c_src/Hacl_Poly1305_32.c -o wasm_src/Hacl_Poly1305_32.wasm.unopt -nostartfiles -Wl,--no-entry -Wl,--export-all
In file included from c_src/Hacl_Poly1305_32.c:25:
In file included from c_src/Hacl_Poly1305_32.h:24:
In file included from /home/docker/hacl-star/dist/kremlin/include/kremlin/internal/types.h:7:
/home/docker/wasi-sdk/wasi-sdk-12.0/lib/clang/11.0.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
#include_next <inttypes.h>
              ^~~~~~~~~~~~
1 error generated.
Makefile:25: recipe for target 'wasm_src/Hacl_Poly1305_32.wasm.unopt' failed
make: *** [wasm_src/Hacl_Poly1305_32.wasm.unopt] Error 1
```

I used the wasi-sdk version 12 and I changed the WASI_CLANG_FLAGS to `-O3 --sysroot=$(WASI_SDK)/share/wasi-sysroot`, but still I can not compile the blade tool. 

Could you help me figure out what is wrong?

**Comment by maxgallup** [comment]
Very strange, because that is exactly the error I had as well and adding the sysroot fixed it for me.

I think the underlying issue is that wasi-sdk-12.0/bin/clang doesn't see the standard C library inside of your docker container, since it's complaining about `<inttypes.h>` which is part of the standard lib. So maybe you could try and see if there is a standard C library installed in your container.

But instinctively, it seems like the issue might be with the docker container. Maybe try ubuntu 22.04 and otherwise if you have a linux machine you could try building it on your host machine outside of the container.

**Comment by Analucar** [comment]
Thank you so much for your help @maxgallup I managed to finally compile the blade tool. My error was in writing the correct path. Instead of --sysroot=$(WASI_SDK)/wasi-sdk-12.0/share/wasi-sysroot I wrote --sysroot=$(WASI_SDK)/share/wasi-sysroot which is a path that does not exist.

Thank you so much!

**Comment by deian** [comment]
woo! glad ya'll resolved it!
